version: 2
updates:
  - package-ecosystem: "pip-compile"
    directory: "/ansible-common"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip-compile"
    directory: "/postgres-dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
