version: 2
updates:
  - package-ecosystem: "pip-compile"
    directory: "/postgres-dev/13"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip-compile"
    directory: "/postgres-dev/14"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip-compile"
    directory: "/postgres-dev/15"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip-compile"
    directory: "/postgres-dev/latest"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip-compile"
    directory: "/postgres-dev/13"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
