# Stop and remove Docker containers
# vars:
#   - docker_compose
#   - host_app_root
---
- name: stop and remove Docker containers
  command: "{{ docker_compose}} down --remove-orphans"
  args:
    chdir: "{{ host_app_root }}"
