# Install docker-engine and docker-compose
# Add users to docker group
# vars:
#   - docker_apt_key_id?
#   - docker_apt_key_url?
#   - docker_repo?
#   - docker_tools_deps_pkgs?: apt packages that Docker needs
---
- name: install package dependencies
  package:
    name: "{{ docker_tools_deps_pkgs }}"
    state: latest

- name: logical volume setup
  command: dmsetup mknodes

- name: add docker apt key
  apt_key:
    url: "{{ docker_apt_key_url }}"
    state: present

- name: add docker repo
  apt_repository:
    repo: "{{ docker_repo }}"

- name: install docker-ce
  package:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    state: latest

- include_tasks: config.yml

- name: start docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: install docker-compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  args:
    warn: false

- file:
    path: /usr/local/bin/docker-compose
    mode: +x
