# Upgrade OS pacakges and Docker tools
---
- name: Upgrade OS packages
  hosts: all
  strategy: free
  remote_user: "{{ root_user | default('root') }}"
  roles:
    - os-install-docker-tools
    - os-safe-upgrade
