name: zBuild and push Docker Image

on:
  workflow_call:
    inputs:
      image_tags:
        type: string
        required: true
        description: image tag name, e.g. ns/image:tag
      context:
        type: string
        default: .
      platforms:
        type: string
        default: linux/amd64
      build-args:
        type: string
        default: ""
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

concurrency:
  group: build-${{ inputs.image_tags }}-${{ inputs.platforms }}
  cancel-in-progress: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          tags: ${{ inputs.image_tags }}
          context: ${{ inputs.context }}
          platforms: ${{ inputs.platforms }}
          build-args: ${{ inputs.build_args }}
          pull: true
          push: true
          cache-to: type=gha,mode=max
          cache-from: type=gha
