name: Build and push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          tags: gsong/nginx
          context: ./nginx
          platforms: linux/amd64
          push: true
          cache-to: type=gha,mode=max
          cache-from: type=gha

  build-postgres:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [13, 14, 15, latest]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          tags: gsong/postgres-dev:${{ matrix.version }}
          context: ./postgres-dev
          build-args: VERSION=${{ matrix.version }}
          platforms: linux/arm64
          push: true
          cache-to: type=gha,mode=max
          cache-from: type=gha
