name: Build and push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-nginx:
    uses: ./.github/workflows/_build_push_image.yaml
    with:
      image_tags: gsong/nginx
      context: ./nginx
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-postgres:
    strategy:
      matrix:
        version: [13, 14, 15, latest]
    uses: ./.github/workflows/_build_push_image.yaml
    with:
      image_tags: gsong/postgres-dev:${{ matrix.version }}
      context: ./postgres-dev
      platforms: linux/arm64
      build-args: VERSION=${{ matrix.version }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
