name: Build and push Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-nginx:
    uses: ./.github/workflows/_build_push_image.yaml
    with:
      tags: gsong/nginx
      context: ./nginx
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-ansible-common:
    uses: ./.github/workflows/_build_push_image.yaml
    with:
      tags: gsong/ansible-common
      context: ./ansible-common
      platforms: linux/arm64
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-postgres-dev:
    strategy:
      matrix:
        version: [13, 14, 15, latest]
    uses: ./.github/workflows/_build_push_image.yaml
    with:
      tags: gsong/postgres-dev:${{ matrix.version }}
      context: ./postgres-dev
      platforms: linux/arm64
      build-args: VERSION=${{ matrix.version }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-postgres-prisma:
    strategy:
      matrix:
        version: [14, 15, latest]
    uses: ./.github/workflows/_build_push_image.yaml
    with:
      tags: gsong/postgres-prisma:${{ matrix.version }}
      context: ./postgres-prisma
      platforms: linux/arm64,linux/amd64
      build-args: VERSION=${{ matrix.version }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
